spring:
  application:
    name: lovable-clone
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB?options=-c%20TimeZone=Asia/Kolkata
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    time-zone: Asia/Kolkata

jwt:
  secret-key: asdfa9023nrkoasdva0asdfs94r523asdf2341238azaf234sdfg45